language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
notifications:
  email: false

env:
  matrix:
    secure: "o+9sCxhhPKYPAD461+0ew5l7Q6AUKVYzvRg/4/HeWRkGUlONt1cT/5BZlQfZquHG2BywSGT9Ng2+o5fgPP2ayRPPsDnm1Y9ulEaLwh1upDiglVjO29WWS6wbPhDzMIiCsDwLITpc3kmjvYMxO/V/BsfHvRsrccuDRq8rzwmG4I15/fXLXtCAzAYHvCmfRQDjgYVjKs11mxKNCvGLjXqQj7Oyv0O/MaKsln68HkUhg9uPU1ZSAwMJFUiKxoyvC4kMPPCac77ZehET7lp7d8bh/q08XESVOztYXiTsVSwBPOKYKkyExHiSTqntFO+no1Yse3i/dxr+20MxoEA4TdFsmIJZce+zOR6S8KIXYNV2hrvZyhUqLBMmng5hYCL7HTKwyW2hvGwjtdDUNGXHKq2FvX3NRsIjDxJaL+3FhqSfW6lReUPei9hq1hpUuasSW4A7Q1dU/wh5DhxQrf5O21V1jcxv470qozKIWLmsHAtcaTx5aKSdGQUWtW0pysAqdHqEN/h5LDCU79E0F2QWxLagmqSO63kS5M7n7ttJkxB8EeL3nF1CqfyXRI8m8HI3g7gmco6s+RGk15dgRq6uE3pIy3N0FsgNHb03Ybv/s+qtesw31nRI2FmX1xajGxiHl2PPPgEjm0OneXdvDBGpvurScUfMenfQWGMSZ9RcoMWpz+k="
